### ISSUE TITLE
Action for publishing to NuGet.org

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/build-script#4]
Make a new Github Action that mirrors current private Jenkins publisher task: 
* transfers all latest packages from GH packages to nuget.org (API key in repo secret)
* pushes scripts to cdn.websharper.com (password in repo secret)
* puts git tags on released commits
* pushes vsix (we would for now just attach it to WebSharper GH release notes, but ideal would be to get out to VS marketplace too)

**Comment by Jand42** [comment]
on the technical side: 
* old publisher still uses Nuget.Core directly for V2 API, GH packages only supports V3, so we can't just copy-paste that code, but use Paket or some other tool (I was looking into NugetDownloader)
* tagging logic on old one uses Jenkins workspace folders, need to check those out in GHA, and then now we can search for correct commit to tag ("Version X" message) as those are now already done during build

**Comment by Jand42** [comment]
I have been experimenting, it's not trivial, writing down my thoughts:

1. Pulling all packages from GH packages is not as straightforward, bc it does not seem to support many of the services that nuget.org has (see json descriptor at https://nuget.pkg.github.com/dotnet-websharper/index.json) and Paket.Core utilities would depend on more for example. But pulling packages from a nuget source to re-upload may not be not the best idea anyways bc GH feed could modify package metadata. So our best option is to go to last build artifacts. Use `gh run download -n Packages` with GH CLI (see https://cli.github.com/manual/gh_actions) in `build-script` repo folder that should download and unpack everything. Note: currently WS.Templates sets vsix project output to folder in a way that a bunch of extra files are zipped from there, clean it up by copying vsix in an after-Compile build step.
2. Publishing to cdn can be copied over from https://bitbucket.org/IntelliFactory/nuget.publisher/src/zafir/src/Publisher.fsx (private repo) mostly: be sure to hide credentials in GH repo secret. Also, we would work from our downloaded list of nupkgs, need testing if NuGet.Core API calls need changes, or we can do what's needed ourselves: unpack nupkg files as a zip, find all dlls under lib and execute PublishCdn logic from BB script.
3. Tagging: we should have all repos in scope pulled in GHA steps as in current build-stack yaml. Then add a new Fake target CI-Tag in websharper50 branch, that's similar to CI-Commit, does not do an actual build, just git operations: search for latest commit by "IntelliFactory CI" user, grab it's commit message, drop the "Version " part, and use the version string as tag on that commit then push tags. This SO question can help https://stackoverflow.com/questions/4404172/how-to-tag-an-older-commit-in-git (we really don't want to tag every release in build-script GHA itself, that would pollute Releases way too much with every internal build as tag)
4. Push vsix: maybe with the GH.Templates mentioned in 1., put vsix on it's own artifact. Then download that and push to websharper.com as in BB script (hide credentials in repo secret). If the release is a preview (has a tag on version), do not set versions.txt so site still shows latest stable but we can directly link to the vsix served from websharper.com. OR: we should finally push to VS marketplace again. Needs credentials from @granicz, hide in repo secret.

**Comment by Tarmil** [comment]
For my personal projects I use https://github.com/dawidd6/action-download-artifact to download artifacts before publishing them. For example: https://github.com/Tarmil/FSharp.SystemTextJson/blob/2fbd6669380d1e2bfb8fdf86ae255af3dec863b6/.github/workflows/publish.yml#L11-L17

**Comment by Jand42** [comment]
Created new ticket #9 for CDN, closing this
