### ISSUE TITLE
GHA for pushing scripts to cdn.websharper.com

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/build-script#9]
Create fsx script based on (closed source) https://bitbucket.org/IntelliFactory/nuget.publisher/src/master/src/Publisher.fsx
This can be executed with `dotnet fsi` from GHA.
GH feed does not support easy enumeration of all packages, it needed, hard-code all packages and the dlls found within them that contain WebSharper .js scripts.

As we don't have all packages readily available, check CDN links first using the hard-coded information on dll names and nuget package versions found in feed, and download only those that are needed.

**Comment by granicz** [comment]
Coming late to the game, here are a few thoughts. First, it's totally fine not to give CDN support for unreleased packages - and remember, anything on GH feed but not on NuGet is "unreleased". Therefore, publishing to CDN can become a post-release step and query public NuGet (which does support what we need for it). Post-release, in case NuGet needs time to sync up after a release.

**Comment by granicz** [comment]
As for the BitBucket link above, that should be then part of the public infrastructure - and brought to GitHub.

**Comment by Jand42** [comment]
Added action publish-cdn, working
